worker_processes 1;
events { worker_connections 1024; }
http {
  sendfile on;

  upstream admin { server admin:5000; }
  upstream aichat { server aichat:5000; }
  upstream application { server application:5000; }
  upstream auth { server auth:5000; }
  upstream chat { server chat:5000; }
  upstream companies { server companies:5000; }
  upstream companyrequests { server companyrequests:5000; }
  upstream files { server files:5000; }
  upstream jobpost { server jobpost:5000; }
  upstream logs { server logs:5000; }
  upstream profiles { server profiles:5000; }

  server {
    listen 80;
    location /admin/ { proxy_pass http://admin/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /aichat/ { proxy_pass http://aichat/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /application/ { proxy_pass http://application/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /auth/ { proxy_pass http://auth/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /chat/ { proxy_pass http://chat/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /companies/ { proxy_pass http://companies/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /companyrequests/ { proxy_pass http://companyrequests/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /files/ { proxy_pass http://files/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /jobpost/ { proxy_pass http://jobpost/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /logs/ { proxy_pass http://logs/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /profiles/ { proxy_pass http://profiles/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
  }
}
